### PR TITLE
Add FLYOVR.IO

### PR DESCRIPTION
**Pull request by ghost64**
Decided to add FLYOVR.IO to my setup after seeing #118 and figuring out the urls and ports from their repos.

Left the Description in deploy-ultrafeeder-container.md blank for @flyovr-io to give me something to add there

### CODE REVIEW

**Comment by dziban303** [comment]
Not crazy about helping to enable some nebulous crypto thing

**Comment by tedder** [comment]
agree, there's no information about people or goals or anything, just "insert adsb, ??, rewards!".

**Comment by flyovr-io** [comment]
Reworking the website is on our to-do list. My name is Eddie, I'm a mechanical engineer. I mainly do product design. The crypto aspect of the project is a way for us to reward data feeders and device owners. We are still working through the legality of everything. I'm not handling the crypto/rewards part of the project. I saw this project and asked to be added to the for-profit list of feeders. I am GENUINELY interested in the idea that we are somehow negative while the existing for-profits exist in positivity? We do ask that everyone is HIGHLY critical of everything we are doing. We want to build something of value for everyone.

**Comment by flyovr-io** [comment]
You can also let me know at my email address, esmith@flyovr.io.

**Comment by dziban303** [comment]
Maybe I'm old fashioned but shouldn't "working through the legality of everything" come *before* you launch your project?

**Comment by flyovr-io** [comment]
It is all legal, I did a poor job in relaying that. We are evaluating what route to take.

**Comment by Taubin** [comment]
https://github.com/sdr-enthusiasts/gitbook-adsb-guide/pull/125#issuecomment-1719948863

I want absolutely nothing to do with anything that has crypto anything. People shouldn't need any form of incentive, especially crypto anything, in order to be willing to feed, aside from _possibly_ extra site features like fr24 does. Adding crypto to anything just screams scam to me and I'm sure many others.

**Comment by flyovr-io** [comment]
Okay, we will create some feature tiers. Feeders will receive our $40M/mo hexadrouple platinum multiplied by gold tier (features tbd). We will also make sure that participating in any kind of data rewards is voluntary via sign up. This is why we super soft launched, we get amazing feedback that helps us create a better product. Thanks!

**Comment by ghost64** [comment]
I didn't realise how shady this was before looking into adding it as a pull request (my bad on my part for just looking at their GitHub and not much else after seeing the issue they created).  I am happy to close this PR off if the community does not want this.

**Comment by dziban303** [comment]
Yeah, they've been saying they were going to redo their homepage for weeks or months.

My take is that if people are motivated enough, they'll figure out how to feed them—after all, it isn't hard. As easy as copypasting boilerplate crypto nothingspeak, you might say. But I don't think this aggregator is one that should be included by default.

**Comment by flyovr-io** [comment]
What issue did we create? If this is affecting your project negatively, by all means remove us. I had a great conversation with someone yesterday that found us via the ultrafeeder. Also, please elaborate on what is shady so we can correct it.

**Comment by flyovr-io** [comment]
Dziban, you started the investigation into us via discord on 8/9. Before that, we were quiet. It wasn't ready, it still isn't. Based on Discord feedback that day, I was very motivated to change the site. The problem is that since then, people signing up to know more vs visitors is favorably high. The wording needs work, the overall message needs work but it isn't a top priority. OS1 is top priority.

**Comment by ghost64** [comment]
> What issue did we create? 

I meant GitHub issue #118

**Comment by ghost64** [comment]
Closing this PR as discussed above.  As @dziban303 says, people can look this PR up if they want the exact information to add it to their ultrafeeder.

**Comment by ghost64** [comment]
Issue #118 should probably be closed too.

**Comment by flyovr-io** [comment]
Got ya, sorry for the misunderstanding. Good luck on the project! We will be more aware of our image before asking for things in the future. That is my bad.

**Pull request closed without merging**
